CREATE TABLE EMPLOYEE (
	EmpNo INT PRIMARY KEY,
	EmpName VARCHAR(30),
	BirthDay DATE,
	DeptNo INT,
	MgrNo INT NOT NULL,
	StartDate DATE,
	Salary MONEY,
	Level SMALLINT,
	Status SMALLINT,
	CONSTRAINT Level_CK CHECK(Level BETWEEN 1 AND 7),
	CONSTRAINT Status_CK CHECK(Status BETWEEN 0 AND 2),
	Note VARCHAR(255)
);

CREATE TABLE SKILL(
	SkillNo INT PRIMARY KEY IDENTITY(1,1),
	SkillName VARCHAR(20),
	Note VARCHAR(255)
);

CREATE TABLE DEPARTMENT(
	DeptNo INT PRIMARY KEY IDENTITY(1,1),
	DeptName VARCHAR(30),
	Note VARCHAR(255)
);

CREATE TABLE EMP_SKILL(
	SkillNo INT FOREIGN KEY REFERENCES SKILL(SkillNo),
	EmpNo INT FOREIGN KEY REFERENCES EMPLOYEE(EmpNo),
	SkillLevel SMALLINT, 
	CONSTRAINT SkillLevel_CK CHECK(SkillLevel BETWEEN 1 AND 3),
	RegDate DATE,
	Description VARCHAR(255),
	PRIMARY KEY (SkillNo,EmpNo)
);