ALTER TABLE EMPLOYEE 
ADD Email VARCHAR(50) UNIQUE;

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT df_MgrNo 
DEFAULT 0 FOR MgrNo,
CONSTRAINT df_Status 
DEFAULT 0 FOR Status 
;

--INSERT INTO EMPLOYEE(EmpNo,EmpName) values (1,'tam');